### ISSUE TITLE
Consider versioning meteor-jspdf following jspdf versioning

### ISSUE THREAD

**Issue by ccortezia** [ChipCastleDotCom/meteor-jspdf#2]
Hi there. Thanks for packaging jspdf for meteor. Is there any special reason you did not replicated the original version numbers of jspdf onto meteor-jspdf ? This convention usually helps package users manage projects.

Cheers

**Comment by chip** [comment]
Hi, I didn't have a reason for that, I just hadn't really thought of it. :smile:  My guess is that I would just edit the `package.js` file. Would you mind sending a PR so that I understand your intention?

Also, please check https://github.com/MrRio/jsPDF/issues/482. I plan to start working on official integration this week with the author of `jsPDF`, so this package will eventually be deprecated.
